// @ts-check
// Single auto-generated sidebar driven by the /docs folder tree.
// Order + labels for each category come from its `_category_.json` file,
// so adding a new guide is just dropping an `.mdx` into the right folder.

/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
  wikiSidebar: [{type: 'autogenerated', dirName: '.'}],
};

export default sidebars;
